services:
  - type: web
    name: route-optimizer
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn test:app
    envVars:
      - key: PYTHONUNBUFFERED
        value: "TRUE"